### ISSUE TITLE
キャッシュの効率・効果を(どうにかして)数値化する

### ISSUE THREAD

**Issue by ghost** [voyagegroup/kusabana#11]

**Comment by ghost** [comment]
Redisのsorted setを使い、アクセスがあった場合にかかった時間をスコアとしてみる。

**Comment by KentaSuzukiVG** [comment]
あと、cacheがヒットしたかしてないかとかの数値をKibanaでいい感じのdashboardにしておくといいね。dashboardのJSONもexportできるから、別環境でもそれが簡単にみられるようになっているとなお良さそう。
